"""Agrega campo turno a Agenda

Revision ID: 1be40ae32754
Revises: 3eedafda1199
Create Date: 2025-11-30 19:59:18.015487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be40ae32754'
down_revision = '3eedafda1199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
