"""Agrega campo modalidad a Agenda

Revision ID: 3eedafda1199
Revises: f8a87f83428b
Create Date: 2025-11-30 19:23:31.165708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eedafda1199'
down_revision = 'f8a87f83428b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidad', sa.String(length=50), nullable=True))

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('sexo')

    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_column('modalidad')

    # ### end Alembic commands ###
