"""Agregar cedula nullable a doctores

Revision ID: 4e32ae3bdb7f
Revises: 69bd5ec67502
Create Date: 2025-11-29 15:27:49.698000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e32ae3bdb7f'
down_revision = '69bd5ec67502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.drop_column('turno')
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
