"""Agregando cascade delete en Agenda

Revision ID: c1915b279517
Revises: 317495cde599
Create Date: 2025-12-10 21:09:05.984579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1915b279517'
down_revision = '317495cde599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agenda_paciente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agenda_paciente_id_fkey'), 'paciente', ['paciente_id'], ['id'])

    # ### end Alembic commands ###
