"""agregar user_id a doctores

Revision ID: d99f2950031c
Revises: 10dd2ed9770f
Create Date: 2025-12-14 11:57:31.982360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99f2950031c'
down_revision = '10dd2ed9770f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminamos las operaciones sobre 'doc' y 'pacientes' porque ya no forman parte del modelo actual

    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # No tocamos las constraints de 'recetario' porque ya están alineadas con doctores/paciente
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # Nota:
    # No recreamos 'doc' ni 'pacientes' porque ya no forman parte del modelo actual.
    # Tampoco tocamos las constraints de 'recetario' porque ya están alineadas con doctores/paciente.
    # ### end Alembic commands ###
